#!/bin/sh

CUR_PATH=$PWD
TEMP_INSTALL_SHELL_PATH=`echo $0 |sed -e 's%/uninstall.sh.*$%%'`

cd $TEMP_INSTALL_SHELL_PATH
INSTALL_SHELL_PATH=$PWD
cd $CUR_PATH

INSTALL_DAEMON_PATH=`echo $INSTALL_SHELL_PATH |sed -e 's%/etc.*$%%'`
INSTALL_OPSHELL_PATH=$INSTALL_DAEMON_PATH/op-shell
INSTALL_UTIL_SHELL_PATH=$INSTALL_OPSHELL_PATH/misc
INSTALL_CFG_PATH=$INSTALL_DAEMON_PATH/cfg
INSTALL_LIB_PATH=/usr/local/lib/db_syncd

SOURCE_ROOT_PATH=$INSTALL_DAEMON_PATH/etc/init.d
SOURCE_DAEMON_BIN_PATH=$SOURCE_ROOT_PATH/bins
SOURCE_OPSHELL_PATH=$SOURCE_ROOT_PATH/op-shell
SOURCE_UTIL_SHELL_PATH=$SOURCE_OPSHELL_PATH/misc
SOURCE_CFG_PATH=$SOURCE_ROOT_PATH/cfg
SOURCE_LIB_PATH=$SOURCE_ROOT_PATH/libs

RULE_SHELL_PATH=$SOURCE_UTIL_SHELL_PATH

UTIL_SHELL=$SOURCE_UTIL_SHELL_PATH/util.sh

source $UTIL_SHELL $SOURCE_UTIL_SHELL_PATH

DAEMON_NAME=`echo $INSTALL_DAEMON_PATH|rev |sed 's%/.*$%%' |rev`

#INODE=`ls -i1 $INSTALL_DAEMON_PATH |grep -w $DAEMON_NAME\$ |sed -e "s/^ *//" -e "s/ .*$//"`

MAJOR_VER=`get_ver "MAJOR_VERSION"`

`$RULE_SHELL_PATH/rule.sh $DAEMON_NAME $MAJOR_VER del_all INPUT`

rm -rf $INSTALL_DAEMON_PATH
rm -rf $INSTALL_LIB_PATH
printf >&1 "[ \033[33m%-39s\033[0m ] %-40s [ \033[32mOK\033[0m ]\n" $DAEMON_NAME "Uninstall..."

exit 9
