
[[jobstatement]]
 Href = "www.exmaple.com/jobstatement/movie/1"
 Movie_id = "1"

[[jobstatement]]
Href = "www.exmaple.com/jobstatement/movie/2"
Movie_id = "2"
 
[[jobstatement]]
Href = "www.exmaple.com/jobstatement/movie/3"
Movie_id = "3"

[[jobstatement]]
Href = "www.exmaple.com/jobstatement/movie/4"
Movie_id = "4"
